version: 2

build:
  os: "ubuntu-24.04"
  tools:
    python: "miniconda3-3.12-24.9"

conda:
  environment: conda/environment.yml

sphinx:
  # Path to your Sphinx configuration file.
  configuration: doc/conf.py
