name: mtg_dev
channels:
  - openalea3/label/dev
  - openalea3/label/rc
  - openalea3
  - conda-forge

dependencies:
  - python
  - openalea.plantgl
  - matplotlib-base
  - pip
  - pip:
    - -e .."[doc, test]"
